### ISSUE TITLE
User Auth

### ISSUE THREAD

**Issue by xxp125** [embedthis/goahead#242]
### Environment

* Windows 10 
* GoAhead V3.6.3
* Personal Computer

### Build
i use vs2012 to build the project.

### Problem Description:
When I login two times, there was a crash whith goahead.

**Comment by atomgunlk** [comment]
Me too.
this is my log

Test scenario 
- from index.html 
- login and redirect to status.asp
- request index.html and login again
- crash!!!


<<< Request
POST /action/login HTTP/1.1
Host: 192.168.11.115:8080
Cookie: -goahead-session-=::webs.session::fa1f92bafb91938e679b25212f6c0dd4
goahead: 5: Examine route /logout/
goahead: 5: Examine route /public/
goahead: 5: Examine route /index.html
goahead: 5: Examine route /action/login
goahead: 5: Route /action/login calls handler action
goahead: 5: User "joshua" authenticated
goahead: 2: Login successful for joshua


>>> Response
HTTP/1.1 302 Redirect
Date: Wed Apr 26 07:37:31 2017
Content-Length: 224
Connection: keep-alive
Location: http://192.168.11.115:8080/status.asp
Set-Cookie: -goahead-session-=::webs.session::fa1f92bafb91938e679b25212f6c0dd4; path=/; domain=192.168.11.115
Cache-Control: no-cache="set-cookie"

<<< Request
GET /status.asp HTTP/1.1
Host: 192.168.11.115:8080
Cookie: -goahead-session-=::webs.session::fa1f92bafb91938e679b25212f6c0dd4
goahead: 5: Examine route /logout/
goahead: 5: Examine route /public/
goahead: 5: Examine route /index.html
goahead: 5: Examine route /
goahead: 5: Examine route /action
goahead: 5: Examine route /
goahead: 5: Route / does not match method GET
goahead: 5: Examine route /
goahead: 5: Route / calls handler jst

>>> Response
HTTP/1.1 200 OK

<<< Request
GET /index.html HTTP/1.1
Host: 192.168.11.115:8080
Cookie: -goahead-session-=::webs.session::fa1f92bafb91938e679b25212f6c0dd4
If-Modified-Since: Wed Apr 26 07:37:20 2017
goahead: 5: Examine route /logout/
goahead: 5: Examine route /public/
goahead: 5: Examine route /index.html
goahead: 5: Route /index.html calls handler file

>>> Response
HTTP/1.1 304 Not Modified

<<< Request
POST /action/login HTTP/1.1
Host: 192.168.11.115:8080
Cookie: -goahead-session-=::webs.session::fa1f92bafb91938e679b25212f6c0dd4
goahead: 5: Examine route /logout/
goahead: 5: Examine route /public/
goahead: 5: Examine route /index.html
goahead: 5: Examine route /action/login
goahead: 5: Route /action/login calls handler action
goahead: 5: User "joshua" authenticated
goahead: 2: Login successful for joshua
goahead: 0: Assertion 0 <= sd && sd < symMax, failed at src/runtime.c 2074

Segmentation fault (core dumped)

**Comment by mobrien** [comment]
Can you please provide a symbolic stack backtrace?

**Comment by mobrien** [comment]
Having trouble reproducing this issue.

What kind of authentication were you using?  Basic, digest or web form?

Can you please provide the HTTP headers at level 4 so we can see the full headers.
